// <auto-generated />
using System;
using DispatchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DispatchService.Migrations
{
    [DbContext(typeof(DispatchServiceContext))]
    partial class DispatchServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DispatchService.Models.Dispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnexoDin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnexoDus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnexoFacturaHYF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDASALUD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificadoOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConocimientoEmbarque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacturaExportacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FacturaHYF")
                        .HasColumnType("bit");

                    b.Property<bool?>("FacturaOrtiz")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFacturacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("GastosDespacho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("IdDespacho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDespachoFlujo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoDespacho")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoFacturacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoPago")
                        .HasColumnType("int");

                    b.Property<int>("IdMensual")
                        .HasColumnType("int");

                    b.Property<int>("IdOperaciones")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoServicios")
                        .HasColumnType("int");

                    b.Property<string>("Iva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListaEmpaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MICDTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mandato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagoTgr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VencimientoDus")
                        .HasColumnType("datetime2");

                    b.Property<string>("referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CMPDispatch");
                });

            modelBuilder.Entity("DispatchService.Models.DispatchAnnexes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDespacho")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDespacho");

                    b.ToTable("CMPDispatchAnnexes");
                });

            modelBuilder.Entity("DispatchService.Models.DispatchAnnexes", b =>
                {
                    b.HasOne("DispatchService.Models.Dispatch", "Dispatch")
                        .WithMany("DispatchAnexes")
                        .HasForeignKey("IdDespacho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatch");
                });

            modelBuilder.Entity("DispatchService.Models.Dispatch", b =>
                {
                    b.Navigation("DispatchAnexes");
                });
#pragma warning restore 612, 618
        }
    }
}
